# Overview

Call

	python3 example.py

should result in two instances of logging to stderr. Only one occurs.
